name: add contributor

on:
  workflow_dispatch:
    inputs:
      name:
        description: new contributor's name
        required: true
      contributions:
        description: comma separated list of contributions types
        required: true

jobs:
  add_contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          cache: 'npm'
      - run: npx all-contributors-cli add ${{github.event.inputs.name}} ${{github.event.inputs.contributions}}
      - run: npx all-contributors-cli generate
      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git add README.md .all-contributorsrc && \
          git commit -m 'add ${{github.event.inputs.name}} contributor for ${{github.event.inputs.contributions}}' && \
          git push